# Dependabot will run on day 12 of each month at 03:12 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "12 3 12 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Author"
    versioning-strategy: "increase"
